import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Read the routes generated by scripts/generate-routes.js.
// Run `node scripts/generate-routes.js` (wired as "prebuild" in
// package.json) before every `vite build` so this file is fresh.
const routesPath = path.join(__dirname, 'scripts', 'routes.json')
const routes = fs.existsSync(routesPath)
  ? JSON.parse(fs.readFileSync(routesPath, 'utf-8'))
  : ['/'] // fallback so a missing routes.json doesn't break local dev builds

// Custom prerender plugin.
//
// We talk to @prerenderer/prerenderer (the actual rendering engine)
// directly instead of using vite-plugin-prerender — that wrapper's
// published build calls require() inside an .mjs file, which throws
// under Node's ESM loader ("require is not defined in ES module
// scope"). @prerenderer/prerenderer itself is fine; only the thin Vite
// wrapper around it was broken.
//
// `apply: 'build'` is critical: it stops this plugin from loading at
// all during `vite dev` / `vite preview`, so it can't crash the dev
// server — only `vite build` ever touches Puppeteer.
function prerenderPlugin() {
  return {
    name: 'custom-prerender',
    apply: 'build',
    async closeBundle() {
      const { default: Prerenderer } = await import('@prerenderer/prerenderer')
      const { default: PuppeteerRenderer } = await import('@prerenderer/renderer-puppeteer')

      const distDir = path.join(__dirname, 'dist')

      // On Vercel, puppeteer's own bundled Chromium can't run — the
      // build container is missing system libs it needs (libnspr4.so,
      // and others further down the chain like libnss3.so). Vercel
      // has no apt-get step available to add them.
      //
      // @sparticuz/chromium ships a Chromium build compiled specifically
      // to run with no external library dependencies in restricted
      // serverless/build containers like Vercel's. We only reach for it
      // when running on Vercel (detected via the VERCEL env var, which
      // Vercel sets automatically) — locally on Windows, launchOptions
      // stays empty and puppeteer uses its normal bundled browser,
      // completely untouched.
      let launchOptions = {}
      if (process.env.VERCEL) {
        const chromium = (await import('@sparticuz/chromium')).default
        launchOptions = {
          args: chromium.args,
          defaultViewport: chromium.defaultViewport,
          executablePath: await chromium.executablePath(),
          headless: chromium.headless,
        }
      }

      const prerenderer = new Prerenderer({
        staticDir: distDir,
        routes,
        server: {
          // On some Windows setups, @prerenderer/prerenderer fails to
          // auto-resolve a hostname for its internal static server and
          // builds a URL like "http://undefined:8000/...". Setting
          // this explicitly avoids that.
          host: '127.0.0.1',
          port: 8000,
        },
        renderer: new PuppeteerRenderer({
          // Event-based capture, not a flat time delay. This is the
          // strategy that correctly captured <head> mutations in our
          // very first successful test (title/meta updates worked).
          // Switching to a flat renderAfterTime later broke title/meta
          // capture even though body content still rendered correctly —
          // whatever @prerenderer/renderer-puppeteer does differently
          // between these two modes, the event-based one is the one
          // that's actually been proven to work here.
          //
          // The event is fired explicitly by BlogPost.jsx/ProjectDetail.jsx
          // once their data loads, and as a fallback after 3s by
          // main.jsx for every other page — see src/main.jsx.
          renderAfterDocumentEvent: 'prerender-ready',
          // Bumped from 4 -> 8 now that product pages (~700 routes) are
          // included alongside blog/project pages. Higher concurrency
          // trades peak memory for total build time; if Vercel's build
          // container starts OOM-ing or randomly failing routes, dial
          // this back down rather than raising it further.
          maxConcurrentRoutes: 8,
          // Slightly higher than the original 20s — with more routes
          // rendering concurrently, individual pages can take a bit
          // longer to hit their 'prerender-ready' event under load.
          timeout: 30000,
          launchOptions,
        }),
      })

      console.log(`[prerender] Rendering ${routes.length} routes...`)

      try {
        await prerenderer.initialize()
        const renderedRoutes = await prerenderer.renderRoutes(routes)

        for (const rendered of renderedRoutes) {
          const outputDir = path.join(distDir, rendered.route)
          fs.mkdirSync(outputDir, { recursive: true })
          fs.writeFileSync(path.join(outputDir, 'index.html'), rendered.html.trim())
        }

        console.log(`[prerender] Wrote ${renderedRoutes.length} prerendered pages.`)
      } finally {
        await prerenderer.destroy()
      }
    },
  }
}

export default defineConfig({
  plugins: [
    react(),
    // Explicitly NOT prerendering /admin/* — that's the separate
    // Admin Dashboard app proxied in during dev, not part of the
    // public site's SEO surface, and often requires auth.
    prerenderPlugin(),
  ],
  server: {
    port: 5173,
    // Dev-time convenience: the Admin Dashboard is a separate Vite app
    // running on its own dev server (port 5174). This proxy makes
    // http://localhost:5173/admin transparently forward to it, so you can
    // type /admin in the SAME browser tab/address bar while both `npm run
    // dev` servers are running, without needing the production build.
    proxy: {
      '/admin': {
        target: 'http://localhost:5174',
        changeOrigin: true,
        ws: true
      }
    }
  }
})