import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// Read the routes generated by scripts/generate-routes.js.
// Run `node scripts/generate-routes.js` (wired as "prebuild" in
// package.json) before every `vite build` so this file is fresh.
const routesPath = path.join(__dirname, 'scripts', 'routes.json')
const routes = fs.existsSync(routesPath)
  ? JSON.parse(fs.readFileSync(routesPath, 'utf-8'))
  : ['/'] // fallback so a missing routes.json doesn't break local dev builds

// Custom prerender plugin.
//
// We talk to @prerenderer/prerenderer (the actual rendering engine)
// directly instead of using vite-plugin-prerender — that wrapper's
// published build calls require() inside an .mjs file, which throws
// under Node's ESM loader ("require is not defined in ES module
// scope"). @prerenderer/prerenderer itself is fine; only the thin Vite
// wrapper around it was broken.
//
// `apply: 'build'` is critical: it stops this plugin from loading at
// all during `vite dev` / `vite preview`, so it can't crash the dev
// server — only `vite build` ever touches Puppeteer.
function prerenderPlugin() {
  return {
    name: 'custom-prerender',
    apply: 'build',
    async closeBundle() {
      const { default: Prerenderer } = await import('@prerenderer/prerenderer')
      const { default: PuppeteerRenderer } = await import('@prerenderer/renderer-puppeteer')

      const distDir = path.join(__dirname, 'dist')

      const prerenderer = new Prerenderer({
        staticDir: distDir,
        routes,
        server: {
          // On some Windows setups, @prerenderer/prerenderer fails to
          // auto-resolve a hostname for its internal static server and
          // builds a URL like "http://undefined:8000/...". Setting
          // this explicitly avoids that.
          host: '127.0.0.1',
          port: 8000,
        },
        renderer: new PuppeteerRenderer({
          // A fixed wait, applied to every route, instead of a custom
          // DOM event — the event approach only works on pages we've
          // wired it into (BlogPost, ProjectDetail). Pages like Home,
          // Products, Blog list, About, etc. never fire it, which was
          // causing Puppeteer to wait the full timeout and fail on the
          // very first route. A flat delay is less precise but works
          // uniformly across every page without touching files we
          // haven't seen.
          renderAfterTime: 5000,
          maxConcurrentRoutes: 4,
          timeout: 20000,
        }),
      })

      console.log(`[prerender] Rendering ${routes.length} routes...`)

      try {
        await prerenderer.initialize()
        const renderedRoutes = await prerenderer.renderRoutes(routes)

        for (const rendered of renderedRoutes) {
          const outputDir = path.join(distDir, rendered.route)
          fs.mkdirSync(outputDir, { recursive: true })
          fs.writeFileSync(path.join(outputDir, 'index.html'), rendered.html.trim())
        }

        console.log(`[prerender] Wrote ${renderedRoutes.length} prerendered pages.`)
      } finally {
        await prerenderer.destroy()
      }
    },
  }
}

export default defineConfig({
  plugins: [
    react(),
    // Explicitly NOT prerendering /admin/* — that's the separate
    // Admin Dashboard app proxied in during dev, not part of the
    // public site's SEO surface, and often requires auth.
    prerenderPlugin(),
  ],
  server: {
    port: 5173,
    // Dev-time convenience: the Admin Dashboard is a separate Vite app
    // running on its own dev server (port 5174). This proxy makes
    // http://localhost:5173/admin transparently forward to it, so you can
    // type /admin in the SAME browser tab/address bar while both `npm run
    // dev` servers are running, without needing the production build.
    proxy: {
      '/admin': {
        target: 'http://localhost:5174',
        changeOrigin: true,
        ws: true
      }
    }
  }
})